### ISSUE TITLE
Handle damage v1

### ISSUE THREAD

**Issue by SiLar92** [inf112-v20/legless-crane#31]
Prior to implementing lasers

- [x] Save player health in player object #63 

- [x] implement handledamage(damage) in player object

- [x] Certain things always does max damage (holes, going off the map) #37 #81

- [x] Player respawns at 0 health? #39 

- [x] upon respawn the player loses one life and is moved to backup point #39
